version: "3.6"

services:
  zomboid-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - "GAME_VERSION=public"
      - "BIND_IP=0.0.0.0"
      - "QUERY_PORT=16261"
      - "GAME_PORT=8766"
    ports:
      - target: 8766
        published: 8766
        protocol: udp
      - target: 16261
        published: 16261
        protocol: udp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
    cap_drop:
      - ALL
